name: Deploy apps

on:
  release:
    types:
      - released

jobs:
  deploy-android:
    name: Deploy Android app
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m')" >> $GITHUB_OUTPUT

      - name: Compute unique version code
        id: version
        run: echo "version=$(git rev-list HEAD --count)" >> $GITHUB_OUTPUT

      - name: Build APK
        run: |
          ./gradlew assembleRelease \
          "-PexternalVersionName=${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}" \
          "-PexternalVersionCode=${{ steps.version.outputs.version }}" \
          "-PenableLogging=false"

      - name: List available Android build tools
        run: ls -l /usr/local/lib/android/sdk/build-tools/

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ vars.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v7.0.1
        with:
          name: apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      - name: Update GitHub release
        uses: ncipollo/release-action@v1.21.0
        with:
          tag: ${{ github.event.release.name }}
          artifacts: ${{ steps.sign_app.outputs.signedReleaseFile }}
          allowUpdates: true
          draft: false
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          replacesArtifacts: false
